import './globals.scss';
import { ThemeProvider } from '@mui/material';
import theme from '../theme';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './shared/globalState/Provider';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'My Cocktail Bar',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider theme={theme}>
          <Providers>
            <Header />

            {children}

            <Footer />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
